# Precision
## Introduction
Precision is the fraction of correct positive predictions out of all positive predictions. It is also known as positive predictive value or Sensitivity.
$$ Precision = \frac{TP}{TP + FP} $$
where,
* TP = True Positive
* FP = False Positive

In [2]:
# importing required libraries
import numpy as np
from warnings import warn

## Use Case
Precision is most useful when we want the prediction to match the actual value as closely as possible. For example, in a medical test, we want to minimize the number of false negatives. In this case, we want to maximize the precision. Because, for example, if we predict that a patient does not have a disease, but he actually has it, then it can be very dangerous for the patient.

In [17]:
# precision score function / Sensitivity / Positive Predictive Value
# precision = tp / (tp + fp)
def precision_score(y_true, y_pred, average='binary', zero_division='warn'):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    
    # for binary classification, we can use the formula straight away
    if average == 'binary':
        assert len(np.unique(y_true)) == 2, 'y_true should have only 2 unique values i.e. binary classification'
        
        tp = np.sum((y_true == 1) & (y_pred == 1))
        fp = np.sum((y_true == 0) & (y_pred == 1))
        
        if tp + fp == 0: # if there are no true positives and false positives, we will get a division by zero error
            if zero_division == 'warn':
                warn("set zero_division to 0 or 1 to avoid this warning. Default is 'warn'")
                return 0 # since x / 0
            elif zero_division == 0:
                return 0
            elif zero_division == 1:
                return 1
            else:
                warn("RuntimeWarning: zero_division must be either 0, 1 or 'warn'")
                return 0 # since x / 0
        else:
            return tp / (tp + fp)
    
    # for multiclass classification, we need to calculate precision for each class
    elif average == 'micro':
        tp = np.sum((y_true == y_pred))
        fp = np.sum((y_true != y_pred))
        
        if tp + fp == 0: # if there are no true positives and false positives, we will get a division by zero error
            if zero_division == 'warn':
                warn("set zero_division to 0 or 1 to avoid this warning. Default is 'warn'")
                return 0 # since x / 0
            elif zero_division == 0:
                return 0
            elif zero_division == 1:
                return 1
            else:
                warn("RuntimeWarning: zero_division must be either 0, 1 or 'warn'")
                return 0 # since x / 0
        else:
            return tp / (tp + fp)
    
    # for multiclass classification, we need to calculate precision for each class and return the mean
    elif average == 'macro':
        classes = np.unique(y_true)
        pre_scores = []
        
        for c in classes:
            tp = np.sum((y_true == c) & (y_pred == c))
            fp = np.sum((y_true != c) & (y_pred == c))
            
            if tp + fp == 0: # if there are no true positives and false positives, we will get a division by zero error
                if zero_division == 'warn':
                    warn("set zero_division to 0 or 1 to avoid this warning. Default is 'warn'")
                    pre_scores.append(0) # since x / 0
                elif zero_division == 0:
                    pre_scores.append(0)
                elif zero_division == 1:
                    pre_scores.append(1)
                else:
                    warn("RuntimeWarning: zero_division must be either 0, 1 or 'warn'")
                    pre_scores.append(0) # since x / 0
            else:
                pre_scores.append(tp / (tp + fp))
            
        return np.mean(pre_scores)
    
    # for multiclass classification, we need to calculate precision for each class and return the score for each class
    elif average == None:
        classes = np.unique(y_true)
        pre_scores = []
        
        for c in classes:
            tp = np.sum((y_true == c) & (y_pred == c))
            fp = np.sum((y_true != c) & (y_pred == c))
            
            if tp + fp == 0: # if there are no true positives and false positives, we will get a division by zero error
                if zero_division == 'warn':
                    warn("set zero_division to 0 or 1 to avoid this warning. Default is 'warn'")
                    pre_scores.append(0) # since x / 0
                elif zero_division == 0:
                    pre_scores.append(0)
                elif zero_division == 1:
                    pre_scores.append(1)
                else:
                    warn("RuntimeWarning: zero_division must be either 0, 1 or 'warn'")
                    pre_scores.append(0) # since x / 0
            else:
                pre_scores.append(tp / (tp + fp))
            
        return np.array(pre_scores)
    
    # Else, we raise an error
    else:
        raise ValueError("average parameter must be 'binary', 'macro', 'micro', or None")

## Testing
The below tests are taken from the Scikit Learn documentation. Source: <https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html>

In [18]:
y_true = [0, 1, 2, 0, 1, 2]
y_pred = [0, 2, 1, 0, 0, 1]

In [19]:
precision_score(y_true, y_pred, average='macro')

0.2222222222222222

In [20]:
precision_score(y_true, y_pred, average='micro')

0.3333333333333333

In [21]:
precision_score(y_true, y_pred, average='weighted')

ValueError: average parameter must be 'binary', 'macro', 'micro', or None

In [22]:
precision_score(y_true, y_pred, average=None)

array([0.66666667, 0.        , 0.        ])

In [23]:
y_pred = [0, 0, 0, 0, 0, 0]
precision_score(y_true, y_pred, average=None)

C:\Users\predator\AppData\Local\Temp\ipykernel_6936\3648799943.py:83: UserWarning: set zero_division to 0 or 1 to avoid this warning. Default is 'warn'
  warn("set zero_division to 0 or 1 to avoid this warning. Default is 'warn'")


array([0.33333333, 0.        , 0.        ])

In [24]:
precision_score(y_true, y_pred, average=None, zero_division=1)

array([0.33333333, 1.        , 1.        ])