# Confusion Matrix
## Introduction
The confusion matrix is a table that is often used to describe the performance of a classification model (or "classifier") on a set of test data for which the true values are known. The confusion matrix itself is relatively simple to understand, but the related terminology can be confusing.  
<pre>
                            |-----------------------------------|  
                            |             Predicted             |  
        Confusion Matrix    |-----------------------------------|  
                            |    Negative     |    Positive     |  
    |-----------------------------------------------------------|  
    |          |  Negative  |  true negative  |  false positive |  
    |  Actual  |------------|-----------------|-----------------|  
    |          |  Positive  |  false negative |  true positive  |  
    |-----------------------------------------------------------|  
    Fig: Confusion Matrix for a Binary classifier (i.e. True/False, Positive/Negative, etc.)
</pre>
<pre>

                           |----------------------------------------|  
                           |             Predicted                  |  
        Confusion Matrix   |----------------------------------------|  
                           |    Cat     |    Dog     |    Mouse     |  
    |---------------------------------------------------------------|  
    |          |    Cat    |      7     |     4      |      4       |
    |          |-----------|------------|---------------------------|  
    |  Actual  |    Dog    |      2     |     7      |      1       |
    |          |-----------|------------|---------------------------|  
    |          |   Mouse   |      1     |     0      |      9       |
    |---------------------------------------------------------------| 
    Fig: Confusion Matrix for a Multi-class classifier (i.e. Cat/Dog/Mouse)
</pre>


In [1]:
# importing required libraries
import numpy as np
import pandas as pd

## Use Case
The confusion matrix is a useful tool for comparing the performance of different models. For example, we might train a logistic regression model and a random forest model, and then compare their confusion matrices to decide which model is better.

In [4]:
# Confusion Matrix Function
def confusion_matrix(y_true, y_pred, labels=None):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)

    assert len(y_true) == len(y_pred), "Length of y_true and y_pred must be equal"

    if labels is None or len(labels) == 0:
        # get all unique labels from both y_true and y_pred
        labels = np.unique(np.append(y_true, y_pred))
    else:
        labels = np.unique(labels)

    len_labels = len(labels)  # number of unique labels
    # create a confusion matrix
    conf_matrix = np.zeros((len_labels, len_labels), dtype=int)

    # fill the confusion matrix
    # for each y_true sample
    for i in range(len(y_true)):
        # iterating over all labels to find the index of y_true sample in labels
        for j in range(len_labels):
            # check for match
            if y_true[i] == labels[j]:
                # iterating over all labels to find the index of y_pred sample in labels
                for k in range(len_labels):
                    # check for match and now for y_pred sample
                    if y_pred[i] == labels[k]:
                        # increment the value of confusion matrix at the index of y_true and y_pred sample
                        conf_matrix[j][k] += 1
                        break  # for optimization
                break  # for optimization

    return conf_matrix

## Testing
The below tests are taken from the Scikit Learn documentation. Source: <https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html>

In [5]:
y_true = [2, 0, 2, 2, 0, 1]
y_pred = [0, 0, 2, 2, 0, 2]
confusion_matrix(y_true, y_pred)

array([[2, 0, 0],
       [0, 0, 1],
       [1, 0, 2]])

In [6]:
y_true = ["cat", "ant", "cat", "cat", "ant", "bird"]
y_pred = ["ant", "ant", "cat", "cat", "ant", "cat"]
confusion_matrix(y_true, y_pred, labels=["ant", "bird", "cat"])

array([[2, 0, 0],
       [0, 0, 1],
       [1, 0, 2]])

We will get 4X4 confusion matrix if we provide 4 classes to the confusion matrix function.

In [7]:
confusion_matrix(y_true, y_pred, labels=["ant", "bird", "cat", "dog"])

array([[2, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 2, 0],
       [0, 0, 0, 0]])